// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace dirien.Vultr
{
    [VultrResourceType("vultr:index/isoPrivate:IsoPrivate")]
    public partial class IsoPrivate : global::Pulumi.CustomResource
    {
        [Output("dateCreated")]
        public Output<string> DateCreated { get; private set; } = null!;

        [Output("filename")]
        public Output<string> Filename { get; private set; } = null!;

        [Output("md5sum")]
        public Output<string> Md5sum { get; private set; } = null!;

        [Output("sha512sum")]
        public Output<string> Sha512sum { get; private set; } = null!;

        [Output("size")]
        public Output<int> Size { get; private set; } = null!;

        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a IsoPrivate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IsoPrivate(string name, IsoPrivateArgs args, CustomResourceOptions? options = null)
            : base("vultr:index/isoPrivate:IsoPrivate", name, args ?? new IsoPrivateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IsoPrivate(string name, Input<string> id, IsoPrivateState? state = null, CustomResourceOptions? options = null)
            : base("vultr:index/isoPrivate:IsoPrivate", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/dirien/pulumi-vultr",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IsoPrivate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IsoPrivate Get(string name, Input<string> id, IsoPrivateState? state = null, CustomResourceOptions? options = null)
        {
            return new IsoPrivate(name, id, state, options);
        }
    }

    public sealed class IsoPrivateArgs : global::Pulumi.ResourceArgs
    {
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public IsoPrivateArgs()
        {
        }
        public static new IsoPrivateArgs Empty => new IsoPrivateArgs();
    }

    public sealed class IsoPrivateState : global::Pulumi.ResourceArgs
    {
        [Input("dateCreated")]
        public Input<string>? DateCreated { get; set; }

        [Input("filename")]
        public Input<string>? Filename { get; set; }

        [Input("md5sum")]
        public Input<string>? Md5sum { get; set; }

        [Input("sha512sum")]
        public Input<string>? Sha512sum { get; set; }

        [Input("size")]
        public Input<int>? Size { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        public IsoPrivateState()
        {
        }
        public static new IsoPrivateState Empty => new IsoPrivateState();
    }
}
