// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.vultr;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DatabaseConnectionPoolArgs extends com.pulumi.resources.ResourceArgs {

    public static final DatabaseConnectionPoolArgs Empty = new DatabaseConnectionPoolArgs();

    /**
     * The logical database to use for the new managed database connection pool.
     * 
     */
    @Import(name="database", required=true)
    private Output<String> database;

    /**
     * @return The logical database to use for the new managed database connection pool.
     * 
     */
    public Output<String> database() {
        return this.database;
    }

    /**
     * The managed database ID you want to attach this connection pool to.
     * 
     */
    @Import(name="databaseId", required=true)
    private Output<String> databaseId;

    /**
     * @return The managed database ID you want to attach this connection pool to.
     * 
     */
    public Output<String> databaseId() {
        return this.databaseId;
    }

    /**
     * The mode to configure for the new managed database connection pool (`session`, `transaction`, `statement`).
     * 
     */
    @Import(name="mode", required=true)
    private Output<String> mode;

    /**
     * @return The mode to configure for the new managed database connection pool (`session`, `transaction`, `statement`).
     * 
     */
    public Output<String> mode() {
        return this.mode;
    }

    /**
     * The name of the new managed database connection pool.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the new managed database connection pool.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The size of the new managed database connection pool.
     * 
     */
    @Import(name="size", required=true)
    private Output<Integer> size;

    /**
     * @return The size of the new managed database connection pool.
     * 
     */
    public Output<Integer> size() {
        return this.size;
    }

    /**
     * The database user to use for the new managed database connection pool.
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return The database user to use for the new managed database connection pool.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private DatabaseConnectionPoolArgs() {}

    private DatabaseConnectionPoolArgs(DatabaseConnectionPoolArgs $) {
        this.database = $.database;
        this.databaseId = $.databaseId;
        this.mode = $.mode;
        this.name = $.name;
        this.size = $.size;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatabaseConnectionPoolArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatabaseConnectionPoolArgs $;

        public Builder() {
            $ = new DatabaseConnectionPoolArgs();
        }

        public Builder(DatabaseConnectionPoolArgs defaults) {
            $ = new DatabaseConnectionPoolArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param database The logical database to use for the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder database(Output<String> database) {
            $.database = database;
            return this;
        }

        /**
         * @param database The logical database to use for the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder database(String database) {
            return database(Output.of(database));
        }

        /**
         * @param databaseId The managed database ID you want to attach this connection pool to.
         * 
         * @return builder
         * 
         */
        public Builder databaseId(Output<String> databaseId) {
            $.databaseId = databaseId;
            return this;
        }

        /**
         * @param databaseId The managed database ID you want to attach this connection pool to.
         * 
         * @return builder
         * 
         */
        public Builder databaseId(String databaseId) {
            return databaseId(Output.of(databaseId));
        }

        /**
         * @param mode The mode to configure for the new managed database connection pool (`session`, `transaction`, `statement`).
         * 
         * @return builder
         * 
         */
        public Builder mode(Output<String> mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param mode The mode to configure for the new managed database connection pool (`session`, `transaction`, `statement`).
         * 
         * @return builder
         * 
         */
        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        /**
         * @param name The name of the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param size The size of the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder size(Output<Integer> size) {
            $.size = size;
            return this;
        }

        /**
         * @param size The size of the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder size(Integer size) {
            return size(Output.of(size));
        }

        /**
         * @param username The database user to use for the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The database user to use for the new managed database connection pool.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public DatabaseConnectionPoolArgs build() {
            $.database = Objects.requireNonNull($.database, "expected parameter 'database' to be non-null");
            $.databaseId = Objects.requireNonNull($.databaseId, "expected parameter 'databaseId' to be non-null");
            $.mode = Objects.requireNonNull($.mode, "expected parameter 'mode' to be non-null");
            $.size = Objects.requireNonNull($.size, "expected parameter 'size' to be non-null");
            $.username = Objects.requireNonNull($.username, "expected parameter 'username' to be non-null");
            return $;
        }
    }

}
