// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.vultr;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.dirien.vultr.ObjectStorageArgs;
import io.dirien.vultr.Utilities;
import io.dirien.vultr.inputs.ObjectStorageState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a Vultr private object storage resource. This can be used to create, read, update and delete object storage resources on your Vultr account.
 * 
 * ## Example Usage
 * 
 * Create a new object storage subscription.
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.vultr.ObjectStorage;
 * import com.pulumi.vultr.ObjectStorageArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var tf = new ObjectStorage(&#34;tf&#34;, ObjectStorageArgs.builder()        
 *             .clusterId(2)
 *             .label(&#34;tf-label&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * Object Storage can be imported using the object storage `ID`, e.g.
 * 
 * ```sh
 *  $ pulumi import vultr:index/objectStorage:ObjectStorage my_s3 0e04f918-575e-41cb-86f6-d729b354a5a1
 * ```
 * 
 */
@ResourceType(type="vultr:index/objectStorage:ObjectStorage")
public class ObjectStorage extends com.pulumi.resources.CustomResource {
    /**
     * The region ID that you want the network to be created in.
     * 
     */
    @Export(name="clusterId", refs={Integer.class}, tree="[0]")
    private Output<Integer> clusterId;

    /**
     * @return The region ID that you want the network to be created in.
     * 
     */
    public Output<Integer> clusterId() {
        return this.clusterId;
    }
    /**
     * Date of creation for the object storage subscription.
     * 
     */
    @Export(name="dateCreated", refs={String.class}, tree="[0]")
    private Output<String> dateCreated;

    /**
     * @return Date of creation for the object storage subscription.
     * 
     */
    public Output<String> dateCreated() {
        return this.dateCreated;
    }
    /**
     * The description you want to give your network.
     * 
     */
    @Export(name="label", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> label;

    /**
     * @return The description you want to give your network.
     * 
     */
    public Output<Optional<String>> label() {
        return Codegen.optional(this.label);
    }
    /**
     * The location which this subscription resides in.
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output<String> location;

    /**
     * @return The location which this subscription resides in.
     * 
     */
    public Output<String> location() {
        return this.location;
    }
    /**
     * The region ID of the object storage subscription.
     * 
     */
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    /**
     * @return The region ID of the object storage subscription.
     * 
     */
    public Output<String> region() {
        return this.region;
    }
    /**
     * Your access key.
     * 
     */
    @Export(name="s3AccessKey", refs={String.class}, tree="[0]")
    private Output<String> s3AccessKey;

    /**
     * @return Your access key.
     * 
     */
    public Output<String> s3AccessKey() {
        return this.s3AccessKey;
    }
    /**
     * The hostname for this subscription.
     * 
     */
    @Export(name="s3Hostname", refs={String.class}, tree="[0]")
    private Output<String> s3Hostname;

    /**
     * @return The hostname for this subscription.
     * 
     */
    public Output<String> s3Hostname() {
        return this.s3Hostname;
    }
    /**
     * Your secret key.
     * 
     */
    @Export(name="s3SecretKey", refs={String.class}, tree="[0]")
    private Output<String> s3SecretKey;

    /**
     * @return Your secret key.
     * 
     */
    public Output<String> s3SecretKey() {
        return this.s3SecretKey;
    }
    /**
     * Current status of this object storage subscription.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Current status of this object storage subscription.
     * 
     */
    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ObjectStorage(String name) {
        this(name, ObjectStorageArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ObjectStorage(String name, ObjectStorageArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ObjectStorage(String name, ObjectStorageArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vultr:index/objectStorage:ObjectStorage", name, args == null ? ObjectStorageArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ObjectStorage(String name, Output<String> id, @Nullable ObjectStorageState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vultr:index/objectStorage:ObjectStorage", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "s3AccessKey",
                "s3SecretKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ObjectStorage get(String name, Output<String> id, @Nullable ObjectStorageState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ObjectStorage(name, id, state, options);
    }
}
