// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.vultr;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class ReverseIpv4Args extends com.pulumi.resources.ResourceArgs {

    public static final ReverseIpv4Args Empty = new ReverseIpv4Args();

    /**
     * The ID of the instance you want to set an IPv4
     * reverse DNS record for.
     * 
     */
    @Import(name="instanceId", required=true)
    private Output<String> instanceId;

    /**
     * @return The ID of the instance you want to set an IPv4
     * reverse DNS record for.
     * 
     */
    public Output<String> instanceId() {
        return this.instanceId;
    }

    /**
     * The IPv4 address used in the reverse DNS record.
     * 
     */
    @Import(name="ip", required=true)
    private Output<String> ip;

    /**
     * @return The IPv4 address used in the reverse DNS record.
     * 
     */
    public Output<String> ip() {
        return this.ip;
    }

    /**
     * The hostname used in the IPv4 reverse DNS record.
     * 
     */
    @Import(name="reverse", required=true)
    private Output<String> reverse;

    /**
     * @return The hostname used in the IPv4 reverse DNS record.
     * 
     */
    public Output<String> reverse() {
        return this.reverse;
    }

    private ReverseIpv4Args() {}

    private ReverseIpv4Args(ReverseIpv4Args $) {
        this.instanceId = $.instanceId;
        this.ip = $.ip;
        this.reverse = $.reverse;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ReverseIpv4Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ReverseIpv4Args $;

        public Builder() {
            $ = new ReverseIpv4Args();
        }

        public Builder(ReverseIpv4Args defaults) {
            $ = new ReverseIpv4Args(Objects.requireNonNull(defaults));
        }

        /**
         * @param instanceId The ID of the instance you want to set an IPv4
         * reverse DNS record for.
         * 
         * @return builder
         * 
         */
        public Builder instanceId(Output<String> instanceId) {
            $.instanceId = instanceId;
            return this;
        }

        /**
         * @param instanceId The ID of the instance you want to set an IPv4
         * reverse DNS record for.
         * 
         * @return builder
         * 
         */
        public Builder instanceId(String instanceId) {
            return instanceId(Output.of(instanceId));
        }

        /**
         * @param ip The IPv4 address used in the reverse DNS record.
         * 
         * @return builder
         * 
         */
        public Builder ip(Output<String> ip) {
            $.ip = ip;
            return this;
        }

        /**
         * @param ip The IPv4 address used in the reverse DNS record.
         * 
         * @return builder
         * 
         */
        public Builder ip(String ip) {
            return ip(Output.of(ip));
        }

        /**
         * @param reverse The hostname used in the IPv4 reverse DNS record.
         * 
         * @return builder
         * 
         */
        public Builder reverse(Output<String> reverse) {
            $.reverse = reverse;
            return this;
        }

        /**
         * @param reverse The hostname used in the IPv4 reverse DNS record.
         * 
         * @return builder
         * 
         */
        public Builder reverse(String reverse) {
            return reverse(Output.of(reverse));
        }

        public ReverseIpv4Args build() {
            $.instanceId = Objects.requireNonNull($.instanceId, "expected parameter 'instanceId' to be non-null");
            $.ip = Objects.requireNonNull($.ip, "expected parameter 'ip' to be non-null");
            $.reverse = Objects.requireNonNull($.reverse, "expected parameter 'reverse' to be non-null");
            return $;
        }
    }

}
