// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.vultr.inputs;

import com.pulumi.core.annotations.Import;
import io.dirien.vultr.inputs.GetObjectStorageClusterFilter;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetObjectStorageClusterPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetObjectStorageClusterPlainArgs Empty = new GetObjectStorageClusterPlainArgs();

    /**
     * Query parameters for finding operating systems.
     * 
     */
    @Import(name="filters")
    private @Nullable List<GetObjectStorageClusterFilter> filters;

    /**
     * @return Query parameters for finding operating systems.
     * 
     */
    public Optional<List<GetObjectStorageClusterFilter>> filters() {
        return Optional.ofNullable(this.filters);
    }

    private GetObjectStorageClusterPlainArgs() {}

    private GetObjectStorageClusterPlainArgs(GetObjectStorageClusterPlainArgs $) {
        this.filters = $.filters;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetObjectStorageClusterPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetObjectStorageClusterPlainArgs $;

        public Builder() {
            $ = new GetObjectStorageClusterPlainArgs();
        }

        public Builder(GetObjectStorageClusterPlainArgs defaults) {
            $ = new GetObjectStorageClusterPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters Query parameters for finding operating systems.
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable List<GetObjectStorageClusterFilter> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters Query parameters for finding operating systems.
         * 
         * @return builder
         * 
         */
        public Builder filters(GetObjectStorageClusterFilter... filters) {
            return filters(List.of(filters));
        }

        public GetObjectStorageClusterPlainArgs build() {
            return $;
        }
    }

}
