// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.vultr.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IsoPrivateState extends com.pulumi.resources.ResourceArgs {

    public static final IsoPrivateState Empty = new IsoPrivateState();

    @Import(name="dateCreated")
    private @Nullable Output<String> dateCreated;

    public Optional<Output<String>> dateCreated() {
        return Optional.ofNullable(this.dateCreated);
    }

    @Import(name="filename")
    private @Nullable Output<String> filename;

    public Optional<Output<String>> filename() {
        return Optional.ofNullable(this.filename);
    }

    @Import(name="md5sum")
    private @Nullable Output<String> md5sum;

    public Optional<Output<String>> md5sum() {
        return Optional.ofNullable(this.md5sum);
    }

    @Import(name="sha512sum")
    private @Nullable Output<String> sha512sum;

    public Optional<Output<String>> sha512sum() {
        return Optional.ofNullable(this.sha512sum);
    }

    @Import(name="size")
    private @Nullable Output<Integer> size;

    public Optional<Output<Integer>> size() {
        return Optional.ofNullable(this.size);
    }

    @Import(name="status")
    private @Nullable Output<String> status;

    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    @Import(name="url")
    private @Nullable Output<String> url;

    public Optional<Output<String>> url() {
        return Optional.ofNullable(this.url);
    }

    private IsoPrivateState() {}

    private IsoPrivateState(IsoPrivateState $) {
        this.dateCreated = $.dateCreated;
        this.filename = $.filename;
        this.md5sum = $.md5sum;
        this.sha512sum = $.sha512sum;
        this.size = $.size;
        this.status = $.status;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IsoPrivateState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IsoPrivateState $;

        public Builder() {
            $ = new IsoPrivateState();
        }

        public Builder(IsoPrivateState defaults) {
            $ = new IsoPrivateState(Objects.requireNonNull(defaults));
        }

        public Builder dateCreated(@Nullable Output<String> dateCreated) {
            $.dateCreated = dateCreated;
            return this;
        }

        public Builder dateCreated(String dateCreated) {
            return dateCreated(Output.of(dateCreated));
        }

        public Builder filename(@Nullable Output<String> filename) {
            $.filename = filename;
            return this;
        }

        public Builder filename(String filename) {
            return filename(Output.of(filename));
        }

        public Builder md5sum(@Nullable Output<String> md5sum) {
            $.md5sum = md5sum;
            return this;
        }

        public Builder md5sum(String md5sum) {
            return md5sum(Output.of(md5sum));
        }

        public Builder sha512sum(@Nullable Output<String> sha512sum) {
            $.sha512sum = sha512sum;
            return this;
        }

        public Builder sha512sum(String sha512sum) {
            return sha512sum(Output.of(sha512sum));
        }

        public Builder size(@Nullable Output<Integer> size) {
            $.size = size;
            return this;
        }

        public Builder size(Integer size) {
            return size(Output.of(size));
        }

        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        public Builder status(String status) {
            return status(Output.of(status));
        }

        public Builder url(@Nullable Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public IsoPrivateState build() {
            return $;
        }
    }

}
