// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.vultr.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAccountResult {
    /**
     * @return The access control list on your Vultr account.
     * 
     */
    private List<String> acls;
    /**
     * @return The current balance on your Vultr account.
     * 
     */
    private Double balance;
    /**
     * @return The email address on your Vultr account.
     * 
     */
    private String email;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The amount of the last payment made on your Vultr account.
     * 
     */
    private Double lastPaymentAmount;
    /**
     * @return The date of the last payment made on your Vultr account.
     * 
     */
    private String lastPaymentDate;
    /**
     * @return The name on your Vultr account.
     * 
     */
    private String name;
    /**
     * @return The pending charges on your Vultr account.
     * 
     */
    private Double pendingCharges;

    private GetAccountResult() {}
    /**
     * @return The access control list on your Vultr account.
     * 
     */
    public List<String> acls() {
        return this.acls;
    }
    /**
     * @return The current balance on your Vultr account.
     * 
     */
    public Double balance() {
        return this.balance;
    }
    /**
     * @return The email address on your Vultr account.
     * 
     */
    public String email() {
        return this.email;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The amount of the last payment made on your Vultr account.
     * 
     */
    public Double lastPaymentAmount() {
        return this.lastPaymentAmount;
    }
    /**
     * @return The date of the last payment made on your Vultr account.
     * 
     */
    public String lastPaymentDate() {
        return this.lastPaymentDate;
    }
    /**
     * @return The name on your Vultr account.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The pending charges on your Vultr account.
     * 
     */
    public Double pendingCharges() {
        return this.pendingCharges;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> acls;
        private Double balance;
        private String email;
        private String id;
        private Double lastPaymentAmount;
        private String lastPaymentDate;
        private String name;
        private Double pendingCharges;
        public Builder() {}
        public Builder(GetAccountResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.acls = defaults.acls;
    	      this.balance = defaults.balance;
    	      this.email = defaults.email;
    	      this.id = defaults.id;
    	      this.lastPaymentAmount = defaults.lastPaymentAmount;
    	      this.lastPaymentDate = defaults.lastPaymentDate;
    	      this.name = defaults.name;
    	      this.pendingCharges = defaults.pendingCharges;
        }

        @CustomType.Setter
        public Builder acls(List<String> acls) {
            this.acls = Objects.requireNonNull(acls);
            return this;
        }
        public Builder acls(String... acls) {
            return acls(List.of(acls));
        }
        @CustomType.Setter
        public Builder balance(Double balance) {
            this.balance = Objects.requireNonNull(balance);
            return this;
        }
        @CustomType.Setter
        public Builder email(String email) {
            this.email = Objects.requireNonNull(email);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder lastPaymentAmount(Double lastPaymentAmount) {
            this.lastPaymentAmount = Objects.requireNonNull(lastPaymentAmount);
            return this;
        }
        @CustomType.Setter
        public Builder lastPaymentDate(String lastPaymentDate) {
            this.lastPaymentDate = Objects.requireNonNull(lastPaymentDate);
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder pendingCharges(Double pendingCharges) {
            this.pendingCharges = Objects.requireNonNull(pendingCharges);
            return this;
        }
        public GetAccountResult build() {
            final var o = new GetAccountResult();
            o.acls = acls;
            o.balance = balance;
            o.email = email;
            o.id = id;
            o.lastPaymentAmount = lastPaymentAmount;
            o.lastPaymentDate = lastPaymentDate;
            o.name = name;
            o.pendingCharges = pendingCharges;
            return o;
        }
    }
}
