// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace dirien.Vultr.Outputs
{

    [OutputType]
    public sealed class LoadBalancerForwardingRule
    {
        /// <summary>
        /// Port on instance side.
        /// </summary>
        public readonly int BackendPort;
        /// <summary>
        /// Protocol on instance side. Possible values: "http", "https", "tcp".
        /// </summary>
        public readonly string BackendProtocol;
        /// <summary>
        /// Port on load balancer side.
        /// </summary>
        public readonly int FrontendPort;
        /// <summary>
        /// Protocol on load balancer side. Possible values: "http", "https", "tcp".
        /// </summary>
        public readonly string FrontendProtocol;
        public readonly string? RuleId;

        [OutputConstructor]
        private LoadBalancerForwardingRule(
            int backendPort,

            string backendProtocol,

            int frontendPort,

            string frontendProtocol,

            string? ruleId)
        {
            BackendPort = backendPort;
            BackendProtocol = backendProtocol;
            FrontendPort = frontendPort;
            FrontendProtocol = frontendProtocol;
            RuleId = ruleId;
        }
    }
}
