// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ediri.Vultr.Inputs
{

    public sealed class KubernetesNodePoolsNodeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Date node was created.
        /// </summary>
        [Input("dateCreated")]
        public Input<string>? DateCreated { get; set; }

        /// <summary>
        /// ID of node.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The label to be used as a prefix for nodes in this node pool.
        /// </summary>
        [Input("label")]
        public Input<string>? Label { get; set; }

        /// <summary>
        /// Status of node.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public KubernetesNodePoolsNodeArgs()
        {
        }
        public static new KubernetesNodePoolsNodeArgs Empty => new KubernetesNodePoolsNodeArgs();
    }
}
