// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Database extends pulumi.CustomResource {
    /**
     * Get an existing Database resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatabaseState, opts?: pulumi.CustomResourceOptions): Database {
        return new Database(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vultr:index/database:Database';

    /**
     * Returns true if the given object is an instance of Database.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Database {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Database.__pulumiType;
    }

    public readonly clusterTimeZone!: pulumi.Output<string | undefined>;
    public readonly databaseEngine!: pulumi.Output<string>;
    public readonly databaseEngineVersion!: pulumi.Output<string>;
    public /*out*/ readonly dateCreated!: pulumi.Output<string>;
    public /*out*/ readonly dbname!: pulumi.Output<string>;
    public /*out*/ readonly host!: pulumi.Output<string>;
    public readonly label!: pulumi.Output<string>;
    public /*out*/ readonly latestBackup!: pulumi.Output<string>;
    public readonly maintenanceDow!: pulumi.Output<string | undefined>;
    public readonly maintenanceTime!: pulumi.Output<string | undefined>;
    public readonly mysqlLongQueryTime!: pulumi.Output<number | undefined>;
    public readonly mysqlRequirePrimaryKey!: pulumi.Output<boolean | undefined>;
    public readonly mysqlSlowQueryLog!: pulumi.Output<boolean | undefined>;
    public readonly mysqlSqlModes!: pulumi.Output<string[] | undefined>;
    public readonly password!: pulumi.Output<string>;
    public readonly plan!: pulumi.Output<string>;
    public readonly planDisk!: pulumi.Output<number>;
    public /*out*/ readonly planRam!: pulumi.Output<number>;
    public /*out*/ readonly planReplicas!: pulumi.Output<number>;
    public /*out*/ readonly planVcpus!: pulumi.Output<number>;
    public /*out*/ readonly port!: pulumi.Output<string>;
    public readonly readReplicas!: pulumi.Output<outputs.DatabaseReadReplica[]>;
    public readonly redisEvictionPolicy!: pulumi.Output<string | undefined>;
    public readonly region!: pulumi.Output<string>;
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly tag!: pulumi.Output<string | undefined>;
    public readonly trustedIps!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly user!: pulumi.Output<string>;

    /**
     * Create a Database resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatabaseArgs | DatabaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DatabaseState | undefined;
            resourceInputs["clusterTimeZone"] = state ? state.clusterTimeZone : undefined;
            resourceInputs["databaseEngine"] = state ? state.databaseEngine : undefined;
            resourceInputs["databaseEngineVersion"] = state ? state.databaseEngineVersion : undefined;
            resourceInputs["dateCreated"] = state ? state.dateCreated : undefined;
            resourceInputs["dbname"] = state ? state.dbname : undefined;
            resourceInputs["host"] = state ? state.host : undefined;
            resourceInputs["label"] = state ? state.label : undefined;
            resourceInputs["latestBackup"] = state ? state.latestBackup : undefined;
            resourceInputs["maintenanceDow"] = state ? state.maintenanceDow : undefined;
            resourceInputs["maintenanceTime"] = state ? state.maintenanceTime : undefined;
            resourceInputs["mysqlLongQueryTime"] = state ? state.mysqlLongQueryTime : undefined;
            resourceInputs["mysqlRequirePrimaryKey"] = state ? state.mysqlRequirePrimaryKey : undefined;
            resourceInputs["mysqlSlowQueryLog"] = state ? state.mysqlSlowQueryLog : undefined;
            resourceInputs["mysqlSqlModes"] = state ? state.mysqlSqlModes : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["plan"] = state ? state.plan : undefined;
            resourceInputs["planDisk"] = state ? state.planDisk : undefined;
            resourceInputs["planRam"] = state ? state.planRam : undefined;
            resourceInputs["planReplicas"] = state ? state.planReplicas : undefined;
            resourceInputs["planVcpus"] = state ? state.planVcpus : undefined;
            resourceInputs["port"] = state ? state.port : undefined;
            resourceInputs["readReplicas"] = state ? state.readReplicas : undefined;
            resourceInputs["redisEvictionPolicy"] = state ? state.redisEvictionPolicy : undefined;
            resourceInputs["region"] = state ? state.region : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["tag"] = state ? state.tag : undefined;
            resourceInputs["trustedIps"] = state ? state.trustedIps : undefined;
            resourceInputs["user"] = state ? state.user : undefined;
        } else {
            const args = argsOrState as DatabaseArgs | undefined;
            if ((!args || args.databaseEngine === undefined) && !opts.urn) {
                throw new Error("Missing required property 'databaseEngine'");
            }
            if ((!args || args.databaseEngineVersion === undefined) && !opts.urn) {
                throw new Error("Missing required property 'databaseEngineVersion'");
            }
            if ((!args || args.label === undefined) && !opts.urn) {
                throw new Error("Missing required property 'label'");
            }
            if ((!args || args.plan === undefined) && !opts.urn) {
                throw new Error("Missing required property 'plan'");
            }
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["clusterTimeZone"] = args ? args.clusterTimeZone : undefined;
            resourceInputs["databaseEngine"] = args ? args.databaseEngine : undefined;
            resourceInputs["databaseEngineVersion"] = args ? args.databaseEngineVersion : undefined;
            resourceInputs["label"] = args ? args.label : undefined;
            resourceInputs["maintenanceDow"] = args ? args.maintenanceDow : undefined;
            resourceInputs["maintenanceTime"] = args ? args.maintenanceTime : undefined;
            resourceInputs["mysqlLongQueryTime"] = args ? args.mysqlLongQueryTime : undefined;
            resourceInputs["mysqlRequirePrimaryKey"] = args ? args.mysqlRequirePrimaryKey : undefined;
            resourceInputs["mysqlSlowQueryLog"] = args ? args.mysqlSlowQueryLog : undefined;
            resourceInputs["mysqlSqlModes"] = args ? args.mysqlSqlModes : undefined;
            resourceInputs["password"] = args ? args.password : undefined;
            resourceInputs["plan"] = args ? args.plan : undefined;
            resourceInputs["planDisk"] = args ? args.planDisk : undefined;
            resourceInputs["readReplicas"] = args ? args.readReplicas : undefined;
            resourceInputs["redisEvictionPolicy"] = args ? args.redisEvictionPolicy : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["tag"] = args ? args.tag : undefined;
            resourceInputs["trustedIps"] = args ? args.trustedIps : undefined;
            resourceInputs["dateCreated"] = undefined /*out*/;
            resourceInputs["dbname"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["latestBackup"] = undefined /*out*/;
            resourceInputs["planRam"] = undefined /*out*/;
            resourceInputs["planReplicas"] = undefined /*out*/;
            resourceInputs["planVcpus"] = undefined /*out*/;
            resourceInputs["port"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["user"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Database.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Database resources.
 */
export interface DatabaseState {
    clusterTimeZone?: pulumi.Input<string>;
    databaseEngine?: pulumi.Input<string>;
    databaseEngineVersion?: pulumi.Input<string>;
    dateCreated?: pulumi.Input<string>;
    dbname?: pulumi.Input<string>;
    host?: pulumi.Input<string>;
    label?: pulumi.Input<string>;
    latestBackup?: pulumi.Input<string>;
    maintenanceDow?: pulumi.Input<string>;
    maintenanceTime?: pulumi.Input<string>;
    mysqlLongQueryTime?: pulumi.Input<number>;
    mysqlRequirePrimaryKey?: pulumi.Input<boolean>;
    mysqlSlowQueryLog?: pulumi.Input<boolean>;
    mysqlSqlModes?: pulumi.Input<pulumi.Input<string>[]>;
    password?: pulumi.Input<string>;
    plan?: pulumi.Input<string>;
    planDisk?: pulumi.Input<number>;
    planRam?: pulumi.Input<number>;
    planReplicas?: pulumi.Input<number>;
    planVcpus?: pulumi.Input<number>;
    port?: pulumi.Input<string>;
    readReplicas?: pulumi.Input<pulumi.Input<inputs.DatabaseReadReplica>[]>;
    redisEvictionPolicy?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
    tag?: pulumi.Input<string>;
    trustedIps?: pulumi.Input<pulumi.Input<string>[]>;
    user?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
    clusterTimeZone?: pulumi.Input<string>;
    databaseEngine: pulumi.Input<string>;
    databaseEngineVersion: pulumi.Input<string>;
    label: pulumi.Input<string>;
    maintenanceDow?: pulumi.Input<string>;
    maintenanceTime?: pulumi.Input<string>;
    mysqlLongQueryTime?: pulumi.Input<number>;
    mysqlRequirePrimaryKey?: pulumi.Input<boolean>;
    mysqlSlowQueryLog?: pulumi.Input<boolean>;
    mysqlSqlModes?: pulumi.Input<pulumi.Input<string>[]>;
    password?: pulumi.Input<string>;
    plan: pulumi.Input<string>;
    planDisk?: pulumi.Input<number>;
    readReplicas?: pulumi.Input<pulumi.Input<inputs.DatabaseReadReplica>[]>;
    redisEvictionPolicy?: pulumi.Input<string>;
    region: pulumi.Input<string>;
    tag?: pulumi.Input<string>;
    trustedIps?: pulumi.Input<pulumi.Input<string>[]>;
}
